service: nutrition

provider:
  name: aws
  runtime: nodejs6.10
  region: us-east-1
  stage: prod

functions:
  helloworld:
    handler: src/nutrition/get.get
    events:
      - http:
          path: nutrition/{upc}
          method: get
          cors: true

plugins:
  - serverless-plugin-optimize

package:
  individually: true
